# Generated by Django 5.2.4 on 2025-07-24 10:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employees_detail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees_detail',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/'),
            preserve_default=False,
        ),
    ]
